//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControlLibrary.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Добавить JS файл 的本地化字符串。
        /// </summary>
        internal static string Dialog_Title_JS_Open {
            get {
                return ResourceManager.GetString("Dialog_Title_JS_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Пн, Вт, Ср, Чт, Пт, Сб, Вс 的本地化字符串。
        /// </summary>
        internal static string DOW_StrArray {
            get {
                return ResourceManager.GetString("DOW_StrArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JS файлы (*.js) | *.js 的本地化字符串。
        /// </summary>
        internal static string FilterJS {
            get {
                return ResourceManager.GetString("FilterJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Разница между конечным и начальным углом не должна превышать 360° 的本地化字符串。
        /// </summary>
        internal static string Hint_360_Text_Circle {
            get {
                return ResourceManager.GetString("Hint_360_Text_Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Предупреждение 的本地化字符串。
        /// </summary>
        internal static string Hint_360_Title {
            get {
                return ResourceManager.GetString("Hint_360_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Названия дней недели, начиная с понедельника, разделенные запятой. 的本地化字符串。
        /// </summary>
        internal static string Hint_DOW {
            get {
                return ResourceManager.GetString("Hint_DOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Названия месяцев шрифтом, разделенные запятой. 的本地化字符串。
        /// </summary>
        internal static string Hint_Month {
            get {
                return ResourceManager.GetString("Hint_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Удалить файл 的本地化字符串。
        /// </summary>
        internal static string Message_Del_Caption {
            get {
                return ResourceManager.GetString("Message_Del_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ошибка 的本地化字符串。
        /// </summary>
        internal static string Message_Error_Caption {
            get {
                return ResourceManager.GetString("Message_Error_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Вы действительно хотите удалить JS файл? 的本地化字符串。
        /// </summary>
        internal static string Message_JS_Del {
            get {
                return ResourceManager.GetString("Message_JS_Del", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ошибка чтения пользовательских скриптов 的本地化字符串。
        /// </summary>
        internal static string Message_ReadScript_Error {
            get {
                return ResourceManager.GetString("Message_ReadScript_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Предупреждение 的本地化字符串。
        /// </summary>
        internal static string Message_Warning_Caption {
            get {
                return ResourceManager.GetString("Message_Warning_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Системный шрифт 的本地化字符串。
        /// </summary>
        internal static string SystemFont {
            get {
                return ResourceManager.GetString("SystemFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Символ &quot;-&quot; 的本地化字符串。
        /// </summary>
        internal static string UCtrl_Text_Opt_Altitude_true {
            get {
                return ResourceManager.GetString("UCtrl_Text_Opt_Altitude_true", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Единицы измерения 的本地化字符串。
        /// </summary>
        internal static string UCtrl_Text_Opt_AmPm_false {
            get {
                return ResourceManager.GetString("UCtrl_Text_Opt_AmPm_false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Стиль Am/Pm 的本地化字符串。
        /// </summary>
        internal static string UCtrl_Text_Opt_AmPm_true {
            get {
                return ResourceManager.GetString("UCtrl_Text_Opt_AmPm_true", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Заглавные буквы 的本地化字符串。
        /// </summary>
        internal static string UCtrl_Text_Opt_SityName_true {
            get {
                return ResourceManager.GetString("UCtrl_Text_Opt_SityName_true", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Десятичный разделитель 的本地化字符串。
        /// </summary>
        internal static string UCtrl_Text_Opt_Sunrise_false {
            get {
                return ResourceManager.GetString("UCtrl_Text_Opt_Sunrise_false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Разделитель 的本地化字符串。
        /// </summary>
        internal static string UCtrl_Text_Opt_Sunrise_true {
            get {
                return ResourceManager.GetString("UCtrl_Text_Opt_Sunrise_true", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Добавлять нули в начале 的本地化字符串。
        /// </summary>
        internal static string UCtrl_Text_Opt_Year_false {
            get {
                return ResourceManager.GetString("UCtrl_Text_Opt_Year_false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Полное написание года 的本地化字符串。
        /// </summary>
        internal static string UCtrl_Text_Opt_Year_true {
            get {
                return ResourceManager.GetString("UCtrl_Text_Opt_Year_true", resourceCulture);
            }
        }
    }
}
