name: Build and Release Watch Face Editor

on:
  workflow_dispatch:  # позволяет запуск вручную
  push:
    tags: "v_*.*"
    branches: "master"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore packages with nuget
        run: |
          choco install nuget.commandline --no-progress
          nuget restore "AmazFit_Editor_(Watch_Face_Type_GT3).sln"

      - name: Build the solution
        run: msbuild "AmazFit_Editor_(Watch_Face_Type_GT3).sln" /p:Configuration=Release

      - name: Prepare portable output
        shell: cmd
        run: |
          mkdir output
          mkdir output\Watch_Face_Editor_(ZeppOS)
          xcopy /s /i /y Watch_Face_Editor\bin\Release\* output\Watch_Face_Editor_(ZeppOS)\
          if exist lib xcopy /s /i /y lib\* output\Watch_Face_Editor_(ZeppOS)\
          if exist images xcopy /s /i /y images\* output\Watch_Face_Editor_(ZeppOS)\
          if exist Watch_Face_Editor.exe.config copy Watch_Face_Editor.exe.config output\Watch_Face_Editor_(ZeppOS)\
          if exist icon.ico copy icon.ico output\Watch_Face_Editor_(ZeppOS)\
          if exist Watch_Face_Editor_Readme.txt copy Watch_Face_Editor_Readme.txt output\Watch_Face_Editor_(ZeppOS)\

      - name: Create ZIP archive
        id: zip
        shell: pwsh
        run: |
          $msg = git log -1 --pretty=format:%s
          $safeName = ($msg -replace '[\\/:*?"<>|]', '_')  # убрать недопустимые символы для имени файла
          $fullSafeName = "WatchFaceEditor_" + $safeName + ".zip"  # убрать недопустимые символы для имени файла
          Compress-Archive -Path output\* -DestinationPath $fullSafeName
          # Compress-Archive -Path output\* -DestinationPath WatchFaceEditor_Portable.zip
          # echo "::set-output name=zip_name::$safeName"
          "zip_name=$fullSafeName" >> $env:GITHUB_OUTPUT
          "zip_tag=$safeName" >> $env:GITHUB_OUTPUT

      - name: Create GitHub Release and upload ZIP
        uses: softprops/action-gh-release@v1
        with:
          # tag_name: ${{ github.ref_name }}
          # name: Release ${{ github.ref_name }}
          tag_name: ${{ steps.zip.outputs.zip_tag }}
          name: Release ${{ steps.zip.outputs.zip_tag }}
          # files: WatchFaceEditor_Portable.zip
          files: ${{ steps.zip.outputs.zip_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
