name: Build and Release Watch Face Editor

on:
  push:
    tags: "v*.*"
    branches: "master"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore packages with nuget
        run: |
          choco install nuget.commandline --no-progress
          nuget restore Watch_Face_Editor.sln

      - name: Build the solution
        run: msbuild Watch_Face_Editor.sln /p:Configuration=Release

      - name: Prepare portable output
        run: |
          mkdir output
          xcopy /s /i /y Watch_Face_Editor\bin\Release\* output\
          if exist lib xcopy /s /i /y lib\* output\
          if exist images xcopy /s /i /y images\* output\
          if exist Watch_Face_Editor.exe.config copy Watch_Face_Editor.exe.config output\
          if exist icon.ico copy icon.ico output\
          if exist Watch_Face_Editor_Readme.txt copy Watch_Face_Editor_Readme.txt output\

      - name: Create ZIP archive
        run: Compress-Archive -Path output\* -DestinationPath WatchFaceEditor_Portable.zip

      - name: Create GitHub Release and upload ZIP
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: WatchFaceEditor_Portable.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
