name: Build and Release Watch Face Editor

on:
  workflow_dispatch:  # позволяет запуск вручную
  push:
    tags: "v *.*"
    branches: "test_action"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore packages with nuget
        run: |
          choco install nuget.commandline --no-progress
          nuget restore "AmazFit_Editor_(Watch_Face_Type_GT3).sln"

      - name: Build the solution
        run: msbuild "AmazFit_Editor_(Watch_Face_Type_GT3).sln" /p:Configuration=Release

      - name: Prepare portable output
        shell: cmd
        run: |
          mkdir output
          mkdir output\Watch_Face_Editor_(ZeppOS)
          xcopy /s /i /y Watch_Face_Editor\bin\Release\* output\Watch_Face_Editor_(ZeppOS)\
          if exist lib xcopy /s /i /y lib\* output\Watch_Face_Editor_(ZeppOS)\
          if exist images xcopy /s /i /y images\* output\Watch_Face_Editor_(ZeppOS)\
          if exist Watch_Face_Editor.exe.config copy Watch_Face_Editor.exe.config output\Watch_Face_Editor_(ZeppOS)\
          if exist icon.ico copy icon.ico output\Watch_Face_Editor_(ZeppOS)\
          if exist Watch_Face_Editor_Readme.txt copy Watch_Face_Editor_Readme.txt output\Watch_Face_Editor_(ZeppOS)\

      - name: Create ZIP archive
        run: |
          $msg = git log -1 --pretty=format:%s
          $safeName = "WatchFaceEditor_" + ($msg -replace '[\\/:*?"<>|]', '_')  # убрать недопустимые символы для имени файла
          # Compress-Archive -Path output\* -DestinationPath "$safeName.zip"
          Compress-Archive -Path output\* -DestinationPath WatchFaceEditor_Portable.zip

      - name: Create GitHub Release and upload ZIP
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: WatchFaceEditor_Portable.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
